{
	"version": 1731298057,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/downloadremovebgpreview-sheet0.png",
		"images/jungleplayorstartbuttonwithstoneandleavesdecorationsinfunnycartoonstyleisolatedonwhitebackgroundgamemenuinterfacedesignuiassetillustrationvectorremovebgpreview-sheet0.png",
		"images/button-sheet0.png",
		"images/downloadremovebgpreview2-sheet0.png",
		"images/duri-sheet0.png",
		"images/laut-sheet0.png",
		"images/downloadremovebgpreview3-sheet0.png",
		"images/air-sheet0.png",
		"images/tanah-sheet0.png",
		"images/batu-sheet0.png",
		"images/imagesremovebgpreview-sheet0.png",
		"images/imagesremovebgpreview2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/m-sheet0.png",
		"images/p-sheet0.png",
		"images/s-sheet0.png",
		"images/v-sheet0.png",
		"images/b-sheet0.png",
		"images/piala-sheet0.png",
		"images/coin-sheet0.png",
		"media/laureate vanoss gaming background music hd - awesome free sound effects (youtube).m4a",
		"media/laureate vanoss gaming background music hd - awesome free sound effects (youtube).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}